name: test
on:
  workflow_dispatch:
  schedule:
    - cron:  '40 9 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'
      - run: pip install requests==2.31.0
      - run: python main.py
